server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: orders-service
          uri: http://orders-service:8081
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1

        - id: payments-service
          uri: http://payments-service:8080
          predicates:
            - Path=/payments/**
          filters:
            - StripPrefix=1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: orders
        url: /orders/v3/api-docs
      - name: payments
        url: /payments/v3/api-docs

